debug

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e # bail if any command fails
+
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
@@ -20,19 +22,21 @@ fi
 MAXMIND_PATH=`cat $ENV_DIR/MAXMIND_PATH`
 MAXMIND_KEY=`cat $ENV_DIR/MAXMIND_KEY`
 
+TAR="$CACHE_DIR/isp.tar.gz"
 DB="$CACHE_DIR/GeoIP2-ISP.mmdb"
 
-if [ ! -f $DB ]; then
+if [ ! -f $TAR ]; then
 	echo "-----> Database does not exist in cache, downloading."
 
-	TAR="$CACHE_DIR/isp.tar.gz"
-
 	curl -o $TAR -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-ISP&suffix=tar.gz&license_key=$MAXMIND_KEY"
+fi
 
+if [ ! -f $DB ]; then
 	echo "-----> Extracting $TAR"
 
 	tar -zxvf $TAR --wildcards --no-anchored --strip=1 '*GeoIP2-ISP.mmdb'
-	rm $TAR
+
+	ls $CACHE_DIR
 fi
 
 SAVE="$BUILD_DIR/$SAVE"
@@ -40,3 +44,4 @@ SAVE="$BUILD_DIR/$SAVE"
 echo "-----> Copying $DB to $SAVE"
 
 cp $DB $SAVE
+rm $TAR
